import tensorflow as tf
tf.compat.v1.disable_eager_execution()
a=tf.constant(10,name='10')
b=tf.constant(20,name='20')
c=tf.constant(30,name='30')
add_op=tf.add(a,b,name='add')
mul_op=tf.multiply(add_op,c,name='mul')
sess=tf.compat.v1.Session()
res=sess.run(mul_op)
print(res)
tf.compat.v1.summary.FileWriter('./log',sess.graph)